kind: Job
apiVersion: batch/v1
metadata:
  name: harv-metdownload-efi-catch-up
  namespace: software-application-innovation-lab-sail-projects-fcd6dfa
  labels:
    job-name: harv-metdownload-efi-catch-up
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 2
  template:
    metadata:
      name: harv-metdownload-efi-catch-up
      labels:
       job-name: harv-metdownload-efi-catch-up
    spec:
      volumes:
        - name: pecan-unconstrained-forecast-project
          persistentVolumeClaim:
            claimName: pecan-unconstrained-forecast-project
      containers:
        - name: harv-metdownload-efi-catch-up
          image: 'quay.io/computateorg/pecan-unconstrained-forecast:latest'
          command:
            - Rscript
            - pecan/scripts/HARV_metdownload_efi.R
            - --jumpback.date=2023-05-23
          env:
            - name: MINIO_HOST
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: BUCKET_HOST
            - name: MINIO_PORT
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: BUCKET_PORT
            - name: BUCKET_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: BUCKET_REGION
            - name: MINIO_BUCKET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: BUCKET_NAME
            - name: MINIO_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: AWS_ACCESS_KEY_ID
            - name: MINIO_SECRET
              valueFrom:
                secretKeyRef:
                  name: s3-bucket
                  key: AWS_SECRET_ACCESS_KEY
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pecan-rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_URI
              value: 'amqp://guest:$(RABBITMQ_PASSWORD)@pecan-rabbitmq/%2F'
            - name: PGHOST
              value: pecan-postgresql.pecan.svc.cluster.local
            - name: PGPORT
              value: '5432'
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pecan-postgresql
                  key: postgresql-password
            - name: BETYUSER
              value: bety
            - name: BETYPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pecan-betydb
                  key: betyPassword
            - name: BETYDATABASE
              value: bety
            - name: NAME
              value: pecan-server
            - name: FQDN
              value: pecan-server-pecan.apps-crc.testing
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: pecan-betydb
                  key: secretKey
            - name: PECAN_HOME
              value: /opt/app-root/src/pecan
            - name: NC_DIR
              value: /opt/app-root/src/forecast_example/GEFS-NC
            - name: CLIM_DIR
              value: /opt/app-root/src/forecast_example/GEFS/noaa_clim
            - name: PROJECT_DIR
              value: /opt/app-root/src/forecast_example
            - name: MINIO_SCHEME
              value: https
            - name: MINIO_PUBLIC
              value: 'FALSE'
          resources:
            limits:
              cpu: '1'
              memory: '10Gi'
            requests:
              cpu: '1'
              memory: '10Gi'
          volumeMounts:
            - name: pecan-unconstrained-forecast-project
              mountPath: /opt/app-root/src
          imagePullPolicy: Always
      restartPolicy: Never
