kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pecan-unconstrained-forecast-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
