kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pecan-unconstrained-forecast-project
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
